services:
  - type: web
    name: fm-extract
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y chromium chromium-driver
      pip install -r requirements.txt
    startCommand: python app.py
    plan: free
